// "use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Button } from "@/components/ui/button";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Movie",
  description: "Generated by create next app",
};

const token = process.env.TOKEN;

async function fetchGenres() {
  const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });

  return await res.json();
}

export default async function RootLayout({ children }) {
  const data = await fetchGenres();

  return (
    <html lang="en">
	  <head>
        <title>Movie Show</title>
        <meta name="description" content="This is the home page of Movie Show" />
      </head>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="min-h-screen flex flex-col">
          <Header className="z-50 relative mb-12" />
            <div className="flex flex-1 mt-20">
              <aside className="hidden md:block bg-gray-100 dark:bg-gray-900 w-full max-w-[200px] p-4 border-r border-gray-300 dark:border-gray-700 fixed inset-0 z-40 overflow-y-scroll">
                <Button variant="ghost" className="w-full justify-start mb-2">
                  <Link href="/" className="flex items-center gap-2">
                    <svg
                      width="15"
                      height="15"
                      viewBox="0 0 15 15"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg">
                      <path
                        d="M3.24182 2.32181C3.3919 2.23132 3.5784 2.22601 3.73338 2.30781L12.7334 7.05781C12.8974 7.14436 13 7.31457 13 7.5C13 7.68543 12.8974 7.85564 12.7334 7.94219L3.73338 12.6922C3.5784 12.774 3.3919 12.7687 3.24182 12.6782C3.09175 12.5877 3 12.4252 3 12.25V2.75C3 2.57476 3.09175 2.4123 3.24182 2.32181ZM4 3.57925V11.4207L11.4288 7.5L4 3.57925Z"
                        fill="currentColor"
                        fillRule="evenodd"
                        clipRule="evenodd"></path>
                    </svg>
                    All Movies
                  </Link>
                </Button>
                {data.genres?.map((genre) => (
                  <Button
                    key={genre.id}
                    variant="ghost"
                    className="w-full justify-start gap-2">
                    <Link
                      href={`/genres/${genre.name}/${genre.id}`}
                      className="flex items-center gap-2">
                      <svg
                        width="15"
                        height="15"
                        viewBox="0 0 15 15"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg">
                        <path
                          d="M3.24182 2.32181C3.3919 2.23132 3.5784 2.22601 3.73338 2.30781L12.7334 7.05781C12.8974 7.14436 13 7.31457 13 7.5C13 7.68543 12.8974 7.85564 12.7334 7.94219L3.73338 12.6922C3.5784 12.774 3.3919 12.7687 3.24182 12.6782C3.09175 12.5877 3 12.4252 3 12.25V2.75C3 2.57476 3.09175 2.4123 3.24182 2.32181ZM4 3.57925V11.4207L11.4288 7.5L4 3.57925Z"
                          fill="currentColor"
                          fillRule="evenodd"
                          clipRule="evenodd"></path>
                      </svg>
                      {genre.name}
                    </Link>
                  </Button>
                ))}
              </aside>
              <main className="sm:ml-0 md:ml-[200px] p-4 w-full overflow-y-auto">
                {children}
              </main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
