import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Button } from "@/components/ui/button";
import Header from "@/components/Header";
import SideBarMenu from "@/components/SideBarMenu";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Movie",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
	  <head>
        <title>Movie Show</title>
        <meta name="description" content="This is the home page of Movie Show" />
      </head>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="min-h-screen flex flex-col">
          <Header className="z-50 sticky top-0 bg-background" />
            <div className="flex flex-1 mt-20">
              <SideBarMenu />
              <main className="sm:ml-0 md:ml-[200px] p-4 w-full overflow-y-auto">
                {children}
              </main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
